name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: write
      id-token: write
    steps:
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Install Windows toolchain
      run: rustup target add x86_64-pc-windows-gnu
    - name: Install clippy
      run: rustup component add clippy
    - name: Install Mingw-w64 toolchain
      run: sudo apt install binutils-mingw-w64-x86-64 gcc-mingw-w64 nsis
    - uses: actions/checkout@v4
    - name: Run clippy
      run: cargo clippy
    - name: Calendar Version
      id: calendar-version
      run: |
        set -x
        readonly VERSION="$(date +%Y%m%d)-${GITHUB_RUN_NUMBER}"
        echo "Version: $VERSION"
        echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
    - name: Build Binary
      env:
        VERSION: ${{ steps.calendar-version.outputs.version }}
      run: cargo build --verbose --target x86_64-pc-windows-gnu -r
    - name: Binary version path
      id: binary-version-path
      env:
        VERSION: ${{ steps.calendar-version.outputs.version }}
      run: |
        set -x
        echo "audioswitch_path=${VERSION}.exe >> "$GITHUB_OUTPUT"
    - name: Version binary
      env:
        FINAL_PATH: ${{ steps.binary-version-path.outputs.audioswitch_path}}
      run: cp target/x86_64-pc-windows-gnu/release/audioswitch.exe $FINAL_PATH
    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-path: ${{ steps.binary-version-path.outputs.audioswitch_path }}
    - name: Create draft pre-release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ steps.calendar-version.outputs.version }}
        tag_name: ${{ steps.calendar-version.outputs.version }}
        files: "audioswitch-*.exe"
        fail_on_unmatched_files: true
        draft: false
        prerelease: false
